---
- name: preparing all servers with common role
  hosts: all
  roles:
        - common
- name: preparing webservers
  hosts: webservers
  roles:
        - nginx
        - php-fpm 
        - varnish
#single server example
#- name: preparing web1.itwnik.com
#  hosts: web1.itwnik.com
#  roles: 
#	- nginx
#	- php-fpm
