---
- name: preparing webservers
  hosts: webservers
  roles:
        - nginx
#        - php-fpm

#single server example
#- name: preparing web1.itwnik.com
#  hosts: web1.itwnik.com
#  roles: 
#	- nginx
#	- php-fpm
